### ISSUE TITLE
[gql_dio_link] Upload Mutation doesn't work

### ISSUE THREAD

**Issue by aaltmayer7** [gql-dart/gql#169]
I'm using gql_dio_link and graphql_flutter v4 because I need interceptor for manage auth cookie with CookieManager like this :     

```dart
dio.interceptors.add(CookieManager(CookieJar()));
```

I got this error during mutation call for upload file : 
```dart
flutter: *** DioError ***:
flutter: uri: http://localhost:4000/graphql
flutter: DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:687:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#4      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#6      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#7      _JsonStringStringifier.printOn (dart:convert/json.dart:876:17)
#8      _JsonStringStringifier.stringify (dart:convert/json.dart:861:5)
#9      JsonEncoder.convert (dart:convert/json.dart:261:30)
#10     JsonCodec.encode (dart:convert/json.dart:171:45)
#11     DefaultTransformer.transformRequest (package:dio/src/transformer.dart:62:21)
#12     DioMixin._transformData (package:dio/src/dio.dart:1014:39)
<…>
```

Here is my graphql client : 
```dart
  final Link link = DioLink(
      '${DotEnv().env['BASE_URL']}/graphql',
      client: httpService.dio,
    );
    client = GraphQLClient(
      cache: GraphQLCache(),
      link: link,
    );
``` 

Mutation : 
```dart
const String uploadFile = """
  mutation uploadRequestedFile(\$requestedFileId: ID!, \$file: Upload!) {
    uploadRequestedFile(requestedFileId: \$requestedFileId, file: \$file) {
      id
      documentUrl
    }
  }
""";
```
```dart
    final QueryResult result = await graphqlService.client.mutate(
      MutationOptions(
        document: gql(uploadFile),
        variables: {
          'file': await imagePickerService.multipartFileFrom(document.file),
          'requestedFileId': document.id,
        },
      ),
    );
```

This problem occurs when serializing the body http.
Therefore i checked HttpLink source code, and here is how httpLink handles this case :
```dart
    final httpBody = _encodeAttempter(
      request,
      (Map body) => json.encode(
        body,
        toEncodable: (dynamic object) =>
            (object is http.MultipartFile) ? null : object.toJson(),
      ),
    )(body);
```

**Comment by TarekkMA** [comment]
Right now `gql_dio_link` don't yet support file uploads.

 It soon will when this PR #157 get merged.

As soon as I get free I will do it asap

**Comment by chuongdevJC** [comment]
> Right now `gql_dio_link` don't yet support file uploads.
> 
> It soon will when this PR #157 get merged.
> 
> As soon as I get free I will do it asap

Hi! Any plan to merge this PR #157?

**Comment by TarekkMA** [comment]
Yeah, I will try to get it merged

**Comment by kateile** [comment]
workaround of uploading files is to use the instance of dio to send naked post to your graphql api. 

```dart
    final Link _dioLink = DioLink(
      graphqlEndpoint,
      client: dio,
    );
```

We use the same dio instance since it is bound to cookies
```dart
//configure dio endpoint
  dio.options.baseUrl = graphqlEndpoint;
```

```dart
/// Apollo Server accepts POST requests with a JSON body.
/// A valid request must contain either a query or an operationName
/// (or both, in case of a named query), and may include variables.
/// https://www.apollographql.com/docs/apollo-server/v1/requests/
Future<QueryResult> sendNakedPostRequest(
  Dio dio, {
  @required DocumentNode node,
  @required String operationName,
  @required Map<String, dynamic> variables,
}) async {
  try {
    final result = await dio.post(
      '/',
      data: FormData.fromMap({
        "query": lang.printNode(node),
        "variables": variables,
        "operationName": operationName,
      }),
      options: Options(
        sendTimeout: 1000 * 30,
        contentType: 'multipart/form-data',
      ),
    );

    return QueryResult(
      source: QueryResultSource.network,
      data: result.data,
    );
  } catch (e) {
    print(e.toString());

    return QueryResult(
      source: QueryResultSource.network,
      exception: OperationException(graphqlErrors: [
        GraphQLError(
          message: 'Something went wrong please update your App',
        )
      ]),
    );
  }
}
```

and above would be used as
```dart
  Future<QueryResult> uploadAvatar(MultipartFile avatar) async {
    final Map<String, MultipartFile> variables = {"input": avatar};

    return sendNakedPostRequest(
      dio,
      node: UploadAvatarMutation().document,
      variables: variables,
      operationName: UploadAvatarMutation().operationName,
    );
  }
```

Above is just a workaround may be it could work

**Comment by teknolojia** [comment]
Needing of upload feature so badly. Any update?

**Comment by TarekkMA** [comment]
Very sorry for the late reply,
I have submitted a PR https://github.com/gql-dart/gql/pull/255.

**Comment by hazzo** [comment]
Please merge this PR is highly necessary. Thanks for the great work!
