### ISSUE TITLE
Exceptions on disposing WebsocketLink

### ISSUE THREAD

**Issue by dopecoder** [gql-dart/gql#260]
There seems to be an issue with disposing WebSocketLink on android and web.

## Android
On disposing connection, StreamSubscription is not cancelled for the listen used in _connect method, this is causing the onDone method to be called after disposing the connection. this raises an expception saying an event cannot be added once it is closed.

```
[ +189 ms] E/flutter (18672): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Cannot add new events after calling
close
[        ] E/flutter (18672): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
[        ] E/flutter (18672): #1      Subject._add (package:rxdart/src/subjects/subject.dart:141:17)
[        ] E/flutter (18672): #2      Subject.add (package:rxdart/src/subjects/subject.dart:135:5)
[        ] E/flutter (18672): #3      WebSocketLink._connect.<anonymous closure> (package:gql_websocket_link/src/link.dart:221:36)
[        ] E/flutter (18672): #4      _rootRun (dart:async/zone.dart:1346:47)
[        ] E/flutter (18672): #5      _CustomZone.run (dart:async/zone.dart:1258:19)
```

## Android and Web
A DOMException is throw on sending a closeReason other than `normal closure - 1000`, in this case  `going away - 1001`.

```
DOMException: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1001 is neither.
```

Will you accept a PR which solves this by :
1. Cancelling stream subscription on dispose
2. Sending an optional closeReason to the WebSocketLink while creating one, so the the user can customize it without having to change the current spec.

**Comment by aramisromero89** [comment]
I have the same problem.

The problem is this line in gql_websocket_link-0.3.1\lib\src\link.dart
await _channel?.sink.close(websocket_status.goingAway);

if you change it to 
await _channel?.sink.close(websocket_status.normalClosure);

then it works.

Can you fix this?
